version: 2
jobs:
  build:
    working_directory: ~/NailShaykhrazievItis/lessonTwo
    docker:
      # specify the version you desire here
      - image: circleci/android:api-27-node8-alpha
    environment:
          JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          paths:
              - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: |
                           sudo chmod +x gradlew
                           ./gradlew androidDependencies
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
              - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
          # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples